services:
  app:
    build:
      context: .
    container_name: glocation-app
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres-db
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
